### ISSUE TITLE
n_gram_creator needs work 

### ISSUE THREAD

**Issue by ad3429** [BusterBeeDavenport/pwp-capstones#2]
`ngram_list.append(list[n] + list[n+1])`

This line is actually just appending the first and second letter of each word. For example, I tested it using the input ['Hello', 'world', 'coding', 'is', 'cool'], and your function returned ['He', 'wo', 'co', 'is', 'co']. It should have returned: ['Hello world', 'world coding', 'coding is', 'is cool']. 

Here is the correct way to write the function, if you want to take a look:

```
def ngram_creator(text_list):
    ngrams   = []
    lastword = None

    for word in text_list:
        if lastword:
            ngrams.append('{} {}'.format(lastword, word))
        lastword = word
    return ngrams

```

**Comment by BusterBeeDavenport** [comment]
Thanks so much. I struggled with this code probably more than anything else. Of course now it makes sense how wrong my code was. I will definitely drop this in to my code and see how it works (correctly).
